#version:
#services:
#networks:
#volumes:
version: "3.8"
services:
  myDb:
    image: postgres
    container_name: myDb
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "ticketing-app"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - initdb:/var/lib/postgresql/data
    networks:
      - webnet
  ticketing-app:
    build: .
    container_name: ticketingapp
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - myDb
networks:
  webnet:
    driver: bridge
volumes:
  initdb: